export const USER_LOGIN = "USER_LOGIN";
export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const USER_LOGOUT = "USER_LOGOUT";
export const SET_INDENT_DATA = "SET_INDENT_DATA";
export const SET_TRANSPORTER_DATA = "SET_TRANSPORTER_DATA";
export const SET_DESTINATIONCITY_DATA = "SET_DESTINATIONCITY_DATA";
export const SET_EPOD_DATA = "SET_EPOD_DATA";
export const SET_PICKLIST_DATA = "SET_PICKLIST_DATA";
export const SET_ORDERTYPE_DATA = "SET_ORDERTYPE_DATA"
export const SET_FROMCITY_DATA = "SET_FROMCITY_DATA"
export const SET_TOCITY_DATA = "SET_TOCITY_DATA"
export const SET_PICKSLIPNO_LIST = "SET_PICKSLIPNO_LIST"
export const SET_PICKSLIPNUMBER_DATA = "SET_PICKSLIPNUMBER_DATA"
export const SET_PICKSLIPPLANSTATUS_DATA = "SET_PICKSLIPPLANSTATUS_DATA"
export const SET_CUSTOMERNAMECODE_DATA = "SET_CUSTOMERNAMECODE_DATA"
export const SET_UPLOADPICKLIST_DATA = "SET_UPLOADPICKLIST_DATA"
export const SET_PICKSLIPDATE_DATA = "SET_PICKSLIPDATE_DATA"
export const SET_PICKLIST_DOWNLOAD = "SET_PICKLIST_DOWNLOAD"
export const SET_DOWNLOAD_ENABLE = "SET_DOWNLOAD_ENABLE"
export const SET_DOWNLOADTEMPLATE_ENABLE = "SET_DOWNLOADTEMPLATE_ENABLE"
export const SET_LOADER_ENABLE = "SET_LOADER_ENABLE"
export const SET_VEHICLETYPE_DATA = "SET_VEHICLETYPE_DATA";
export const SET_UPDATE_INDENT_DATA = "SET_UPDATE_INDENT_DATA";
export const SET_NUMBER_OF_ITEMS = "SET_NUMBER_OF_ITEMS";
export const SET_TRANSPORTER_ALL_DATA = "SET_TRANSPORTER_ALL_DATA";
export const SET_REFETCH_ENABLE = "SET_REFETCH_ENABLE";
export const SET_PICKLIST_ID_LIST = "SET_PICKLIST_ID_LIST";
export const SET_AUTO_DISPATCH_ID_LIST = "SET_AUTO_DISPATCH_ID_LIST";
export const SET_AUTO_DISPATCH = "SET_AUTO_DISPATCH";
export const SET_AUTO_DISPATCH_PLANNING = "SET_AUTO_DISPATCH_PLANNING";
export const SET_ORDERTYPE = "SET_ORDERTYPE";
export const SET_LR_DATA = "SET_LR_DATA";
export const SET_LR_IDS = "SET_LR_IDS";
export const SET_PLANTRIP_DATA = "SET_PLANTRIP_DATA";
export const SET_LRNO_DATA = "SET_LRNO_DATA";
export const SET_INVOICE_NUMBER = "SET_INVOICE_NUMBER";
export const SET_INVOICE_READY = "SET_INVOICE_READY";
export const SET_CONSIGNEE_NAME = "SET_CONSIGNEE_NAME";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_LOCATION_ID = "SET_LOCATION_ID";
export const SET_LOCATIONBRANCH_ID = "SET_LOCATIONBRANCH_ID";
export const SET_LOCATION_LIST = "SET_LOCATION_LIST";
export const SET_TENANT_ID = "SET_TENANT_ID";
export const SET_ROLE_DATA = "SET_ROLE_DATA";
export const SET_ROLE_OF_USER = "SET_ROLE_OF_USER";
export const SET_USER_ID = "SET_USER_ID";
export const SET_WAREHOUSE_ID = "SET_WAREHOUSE_ID";
export const SET_CONFIRMTRIP_DATA = "SET_CONFIRMTRIP_DATA"
export const SET_CONFIRMTRIP_IDS = "SET_CONFIRMTRIP_IDS"
export const SET_CONSIGNORLIST_DATA = "SET_CONSIGNORLIST_DATA"
export const SET_TRANSPORTERLIST_DATA = "SET_TRANSPORTERLIST_DATA"
export const SET_VEHICLELIST_DATA = "SET_VEHICLELIST_DATA"
export const SET_INVOICE_LIST = "SET_INVOICE_LIST"
export const SET_CUSTOMERMASTER_DATA = "SET_CUSTOMERMASTER_DATA"
export const SET_CUSTOMERMASTER__IDS = "SET_CUSTOMERMASTER__IDS"
export const SET_YARDMANAGEMENT_DATA = "SET_YARDMANAGEMENT_DATA"
export const SET_VEHICLEMASTER_DATA = "SET_VEHICLEMASTER_DATA"
export const SET_LOCATIONMASTER_DATA = "SET_LOCATIONMASTER_DATA"
export const SET_LOCATIONMASTER__IDS = "SET_LOCATIONMASTER__IDS"
export const SET_TRACKANDTRACE_DATA = "SET_TRACKANDTRACE_DATA"
export const SET_SUPPLIERMASTER_DATA = "SET_SUPPLIERMASTER_DATA"
export const SET_SUPPLIERMASTER__IDS = "SET_SUPPLIERMASTER__IDS"
export const SET_SKUMASTER_DATA = "SET_SKUMASTER_DATA"
export const SET_SKUMASTER__IDS = "SET_SKUMASTER__IDS"
export const SET_CONTACTMASTER_DATA = "SET_SKUMASTER_DATA"
export const SET_CONTACTMASTER__IDS = "SET_CONTACTMASTER__IDS"
export const SET_TATMASTER_DATA = "SET_TATMASTER_DATA"
export const SET_TATMASTER__IDS = "SET_TATMASTER__IDS"
export const SET_EWAY_DATA = "SET_EWAY_DATA"
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES"
export const SET_MATRIX_FLOW = "SET_MATRIX_FLOW"
export const SET_MANAGE_USERS = "SET_MANAGE_USERS"
export const SET_MATRIX_FLOW_ADD_EDIT = "SET_MATRIX_FLOW_ADD_EDIT"
export const SET_MATRIX_FLOW_ADD_EDIT_POPUP = "SET_MATRIX_FLOW_ADD_EDIT_POPUP"
export const SET_ADD_EDIT = "SET_ADD_EDIT"
export const SET_ADD_EDIT_POPUP = "SET_ADD_EDIT_POPUP"
export const SET_TRANSPCONTRACTMASTER_DATA = "SET_TRANSPCONTRACTMASTER_DATA"
export const SET_TRANSPCONTRACTMASTER_IDS = "SET_TRANSPCONTRACTMASTER_IDS"
export const SET_TRANSPFREIGHTMASTER_DATA = "SET_TRANSPFREIGHTMASTER_DATA"
export const SET_TRANSPFREIGHTMASTER_IDS = "SET_TRANSPFREIGHTMASTER_IDS"
export const SET_ORGNAME_DATA = "SET_ORGNAME_DATA"
export const SET_ORGCODELIST_DATA = "SET_ORGCODELIST_DATA"
export const SET_STARTUT_DATA = "SET_STARTUT_DATA"
export const SET_CUSTOMERNAME_LIST = "SET_CUSTOMERNAME_LIST"
export const SET_CUSTOMERCODE_LIST = "SET_CUSTOMERCODE_LIST"
export const SET_STATECODE_LIST = "SET_STATECODE_LIST"
export const SET_CITYCODE_LIST = "SET_CITYCODE_LIST"
export const SET_POSTALCODE_LIST = "SET_POSTALCODE_LIST"
export const SET_SHIPPINGBACKORDERS_DATA = "SET_SHIPPINGBACKORDERS_DATA"
export const SET_SUPPLIERCODE_DATA = "SET_SUPPLIERCODE_DATA"
export const SET_WAREHOUSECODE_DATA = "SET_WAREHOUSECODE_DATA"
export const SET_SKUSUPPLIERCODE_DATA = "SET_SKUSUPPLIERCODE_DATA"
export const SET_SKUCODE__DATA = "SET_SKUCODE__DATA"
export const SET_SKUBRAND__DATA = "SET_SKUBRAND__DATA"
export const SET_SIDE_SHOW = "SET_SIDE_SHOW"
export const SET_SYNCSTATUS_DATA = "SET_SYNCSTATUS_DATA"
export const SET_SYNCSTATUS__IDS = "SET_SYNCSTATUS__IDS"
export const SET_LRFILTERTYPE = "SET_LRFILTERTYPE"
export const SET_MANAGE_PERMISSION = "SET_MANAGE_PERMISSION"
export const SET_ADD_EDIT_POPUP_PERMISSION = "SET_ADD_EDIT_POPUP_PERMISSION"
export const SET_ADD_EDIT_PERMISSION = "SET_ADD_EDIT_PERMISSION"
export const SET_REPORTGENERATION_DATA = "SET_REPORTGENERATION_DATA"
export const SET_REPORTGENERATION_IDS = "SET_REPORTGENERATION_IDS"
export const SET_REPORTLIST_DATA = "SET_REPORTLIST_DATA"
export const SET_NAMEOFREPORT = "SET_NAMEOFREPORT"
export const SET_ROUTECITY_PRIMARY_DATA = "SET_ROUTECITY_PRIMARY_DATA"
export const SET_ROUTECITY_SECONDARY_DATA = "SET_ROUTECITY_SECONDARY_DATA"
export const SET_VEHICLERECEIPTROUTE_DATA = "SET_VEHICLERECEIPTROUTE_DATA"
export const SET_DARK_MODE = "SET_DARK_MODE"
export const SET_USERNAME_LIST = "SET_USERNAME_LIST"
export const SET_ROLE_LIST = "SET_ROLE_LIST"
export const SET_MODULE_LIST = "SET_MODULE_LIST"
export const SET_USER_STATUS = "SET_USER_STATUS"
export const SET_REPORTGENERATIONLVL1_DATA = "SET_REPORTGENERATIONLVL1_DATA"
export const SET_REPORTGENERATIONLVL2_DATA = "SET_REPORTGENERATIONLVL2_DATA"
export const SET_REPORTGENERATIONLVL3_DATA = "SET_REPORTGENERATIONLVL3_DATA"
export const SET_LISTOFPARAMSLVL1 = "SET_LISTOFPARAMSLVL1"
export const SET_LISTOFPARAMSLVL2 = "SET_LISTOFPARAMSLVL2"
export const SET_REPORTORDERTYPE = "SET_REPORTORDERTYPE"
export const SET_REPORTTABLENAME = "SET_REPORTTABLENAME"
export const SET_LISTOFPARAMSLVL3 = "SET_LISTOFPARAMSLVL3"
export const SET_REPORTSTARTDATE = "SET_REPORTSTARTDATE"
export const SET_REPORTENDDATE = "SET_REPORTENDDATE"
export const SET_REPORTNAME = "SET_REPORTNAME"
export const SET_VEHICLETYPEMASTER_DATA = "SET_VEHICLETYPEMASTER_DATA"
export const SET_APPROVALMNGT_DATA = "SET_APPROVALMNGT_DATA"
export const SET_APPROVALMNGT__IDS = "SET_APPROVALMNGT__IDS"
export const SET_MODULETYPE_DATA = "SET_MODULETYPE_DATA"
export const SET_FBA_DATA = "SET_FBA_DATA"
export const SET_FBA_DETAILS = "SET_FBA_DETAILS"

















